"use strict";

// "crypto" is Node's built-in cryptography module.
// It wraps the underlying OpenSSL library and gives us tools for
// hashing, random number generation, and safe comparisons.
const crypto = require("crypto");

// scrypt is a "password hashing function" — it is intentionally slow and
// memory-intensive so that an attacker who steals the database cannot
// quickly try millions of guesses (a "brute-force" attack).
// We use it for both user passwords and API keys.
// "sync" means it blocks Node's event loop while computing — that is
// acceptable here because we only call it during login/key-verify operations.
function deriveScryptHash(secret, salt) {
  // crypto.scryptSync(password, salt, keyLength):
  //   - password: the thing to hash (a string or Buffer)
  //   - salt: random bytes mixed in so two identical passwords produce different hashes
  //   - 64: produce 64 bytes of output (512 bits)
  // .toString("hex") converts the raw bytes to a readable hex string.
  return crypto.scryptSync(secret, salt, 64).toString("hex");
}

// Public function used when creating a new user or when rotating a password.
// "salt" is a 16-byte random hex string generated by the caller each time.
function hashPassword(password, salt) {
  // scrypt is deliberately slow, which makes stolen password hashes harder to crack.
  return deriveScryptHash(password, salt);
}

// Public function used at login time to check if a supplied password is correct.
// We never un-hash a password (that's impossible with a one-way hash function).
// Instead we re-hash the candidate and compare.
function verifyPassword(password, hash, salt) {
  // First, compute what the hash SHOULD be for this password + salt combination.
  const expected = Buffer.from(hash, "hex");

  // Then compute what the hash IS for the password the user just typed.
  const actual = Buffer.from(deriveScryptHash(password, salt), "hex");

  // crypto.timingSafeEqual does a byte-by-byte comparison that always takes
  // the SAME amount of time regardless of how many bytes match.
  // A regular === comparison would return faster when the first byte differs,
  // and an attacker measuring response times could use that to guess the hash.
  // We also check the lengths first because timingSafeEqual throws if the
  // buffers are different lengths.
  return expected.length === actual.length && crypto.timingSafeEqual(expected, actual);
}

// Same approach as password hashing, but used for API keys.
// API keys are longer random strings, not user-chosen passwords,
// but we still hash them so the database never stores the raw secret.
function hashApiKey(apiKey, salt) {
  return deriveScryptHash(apiKey, salt);
}

// Called when the Python companion submits a request.
// We hash the incoming key and compare it to the stored hash.
function verifyApiKey(apiKey, hash, salt) {
  // Identical pattern to verifyPassword — hash the candidate and compare safely.
  const expected = Buffer.from(hash, "hex");
  const actual = Buffer.from(deriveScryptHash(apiKey, salt), "hex");
  return expected.length === actual.length && crypto.timingSafeEqual(expected, actual);
}

// Export the four public functions so other modules can use them.
module.exports = {
  hashPassword,
  verifyPassword,
  hashApiKey,
  verifyApiKey
};
